apiVersion: v1
kind: Service
metadata:
  name: hello-world-react-service
spec:
  selector:
    app: hello-world-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008  # Optional: Specify a NodePort in the range 30000-32767
  type: NodePort
